version: '2'
services:
  mysql:
    image: mariadb:10.1.14
    container_name: mds_backoffice_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./private/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mds
      - MYSQL_DATABASE=mds
      - MYSQL_USER=mds
      - MYSQL_PASSWORD=mds